### ISSUE TITLE
Dependency Analysis Error is not being solved 

### ISSUE THREAD

**Issue by meghanarora** [lukaskubanek/LoremSwiftum#16]
When I try to build this, I get the following error: 

"“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

I have tried changing the build settings and tried to convert to current Swift Syntax, but neither has been successful, any thoughts?

**Comment by lukaskubanek** [comment]
What Xcode version are you using?

**Comment by lukaskubanek** [comment]
Closed for no response.
